=== lzaagg/yabi/yabi/yabi-mw/cfg/baat.dtd
<!ELEMENT baat (job+)>
<!ELEMENT job (inputFile, outputFile, parameterList, parameterAliasList, grendel, priority, executionHost, batchNumber, status, startTime, stopTime, submittedTime, submitUser, submitLabel)>
<!ELEMENT inputFile (#PCDATA)>
<!ELEMENT outputFile (#PCDATA)>
<!ELEMENT parameterList (parameter+)>
<!ELEMENT parameterAliasList (parameterAlias+)>
<!ELEMENT grendel (option*)>
<!ELEMENT priority (#PCDATA)>
<!ELEMENT executionHost (#PCDATA)>
<!ELEMENT batchNumber (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT startTime (#PCDATA)>
<!ELEMENT stopTime (#PCDATA)>
<!ELEMENT submittedTime (#PCDATA)>
<!ELEMENT submitUser (#PCDATA)>
<!ELEMENT submitLabel (#PCDATA)>
<!ELEMENT parameter (#PCDATA)>
<!ELEMENT option (name, value)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST job toolPath CDATA #IMPLIED>
<!ATTLIST job toolName CDATA #IMPLIED>
<!ATTLIST parameter name CDATA #IMPLIED>
<!ATTLIST parameter mandatory CDATA #IMPLIED>
<!ATTLIST parameter switchUse CDATA #IMPLIED>
<!ATTLIST parameter switch CDATA #IMPLIED>
<!ATTLIST parameter value CDATA #IMPLIED>
<!ATTLIST parameter rank CDATA #IMPLIED>
<!ATTLIST parameter inputFile CDATA #IMPLIED>
<!ATTLIST parameter outputFile CDATA #IMPLIED>
<!ATTLIST parameterAlias switchAlias CDATA #IMPLIED>
<!ATTLIST parameterAlias switch CDATA #IMPLIED>
<!ATTLIST parameterAlias switchValue CDATA #IMPLIED>
<!ATTLIST grendel id CDATA #IMPLIED>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/pimsblastscorer.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/local/grendel/bin/ccg-pimsblastscorerWrapper" toolName="ccg-pimsblastscorer" displayName="pi-msblast scorer" description="Scores msblast hits.">

    <inputFile/>
    <outputFile/>

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>new</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension>html</extension>
    </outputFiletypes>

    <parameterList>
      <parameter rank="1" switchUse="valueOnly" switch="inputFiles" mandatory="yes" inputFile="yes" outputFile="no" value=""/>
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/blast2html.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/local/grendel/bin/ccg-blast2htmlWrapper" toolName="ccg-blast2html" displayName="blast prettyprint" description="HTML format the output files from BLAST.">

    <inputFile/>
    <outputFile/>

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>bls</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension>html</extension>
    </outputFiletypes>

    <parameterList>
      <parameter rank="1" switchUse="valueOnly" switch="inputFiles" mandatory="yes" filter="prependUserDir" inputFile="yes" outputFile="no" value=""/>
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/amos2frg.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/local/grendel/bin/amos2frgWrapper" toolName="amos2frg" displayName="amos2frg" description="convert from an AMOS message file to a frg file">

    <inputFile/>
    <outputFile/>

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>afg</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension mustExist="true">frg</extension>
    </outputFiletypes>

    <parameterList>
      <parameter rank=""  switchUse="both"       switch="-i"       mandatory="yes" inputFile="yes" outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-o"       mandatory="no" inputFile="no"  outputFile="yes" value="" />
      <parameter rank=""  switchUse="both"       switch="-a"       mandatory="no"  inputFile="no"  outputFile="no"  value="" />
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/renderyabisimple.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/local/bin/ccg-renderyabisimple" toolName="renderyabisimple" displayName="yabi to html" description="Render simple HTML version of yabi format file.">

    <inputFile/>
    <outputFile/>

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>xml</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension>html</extension>
    </outputFiletypes>

    <parameterList>
      <parameter rank="1" switchUse="valueOnly" switch="inputFiles" mandatory="yes" filter="prependUserDir" inputFile="yes" outputFile="no" value=""/>
      <parameter rank="2" switchUse="valueOnly" switch="" mandatory="yes" inputFile="no" outputFile="no" value="output.html"/>
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/runCA.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/local/grendel/bin/runCAWrapper" toolName="runCA" displayName="celera" description="Run a whole-genome shotgun assembly using Celera Assembler">

    <inputFile/>
    <outputFile/>

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>frg</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension>*</extension>
    </outputFiletypes>


    <parameterList>
      <parameter rank=""  switchUse="both"       switch="-d"       mandatory="yes" inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-p"       mandatory="yes" inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-s"       mandatory="yes" inputFile="maybe" outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-help"    mandatory="no"  inputFile="no"  outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-version" mandatory="no"  inputFile="no"  outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-fields"  mandatory="no"  inputFile="no"  outputFile="no"  value="" />
      <parameter rank=""  switchUse="valueOnly"  switch="fragFile" mandatory="yes" inputFile="yes" outputFile="no"  value="" />
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/crossmatch.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/local/grendel/bin/cross_matchWrapper" toolName="cross_match" displayName="cross match" description="Screens fasta file for vector sequences. Your vector file should have a suffix of .vector and be selected by adding a file select task above this task. You should then select appropriate inputs in the options below.">

    <inputFile/>
    <outputFile/>

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>fa</extension>
        <extension>fna</extension>
        <extension>faa</extension>
        <extension>vector</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false" symlinkOutputDir="true">
        <extension>fa</extension>
    </outputFiletypes>

    <parameterList>
      <parameter rank="1" switchUse="valueOnly"  switch="inputFiles" mandatory="yes" inputFile="yes" inputType="file" outputFile="no" value="">
        <inputExtension>qual</inputExtension>
      </parameter>
      <parameter rank="2" switchUse="valueOnly"  switch="vector" mandatory="yes" inputFile="yes" inputType="file" outputFile="no"  value=""/>
      <parameter rank=""  switchUse="both"       switch="-penalty"         mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-gap_init"        mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-gap_ext"         mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-ins_gap_ext"     mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-del_gap_ext"     mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-matrix"          mandatory="no"  inputFile="maybe" inputType="file"        outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-raw"             mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-minmatch"        mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-maxmatch"        mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-max_group_size"  mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-word_raw"        mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-bandwidth"       mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-minscore"        mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-vector_bound"    mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-masklevel"       mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-default_qual"    mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-tags"            mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-screen"          mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="">
        <outputExtension>screen</outputExtension>
      </parameter>
      <parameter rank=""  switchUse="switchOnly" switch="-alignments"      mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-discrep_lists"   mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-discrep_tables"  mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-indexwordsize"   mandatory="no"  inputFile="no"    inputType=""            outputFile="no"  value="" />
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/phred.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/local/grendel/bin/phredWrapper" toolName="phred" displayName="phred" description="Assembles ab1 files. Requires a tar file as input.">

    <inputFile/>
    <outputFile/>

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>tar</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="true" symlinkOutputDir="true">
        <extension>fa</extension>
    </outputFiletypes>

    <parameterList>
      <parameter rank=""  switchUse="both"       switch="-if"              mandatory="no"  inputFile="yes" inputType="listoffiles" outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-id"              mandatory="no"  inputFile="yes" inputType="directory"   outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-zd"              mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-zt"              mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-st"              mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-s"               mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-sa"              mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-sd"              mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-qt"              mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-q"               mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-qa"              mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-qd"              mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-qr"              mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-p"               mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-pd"              mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-cv"              mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-cp"              mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-cs"              mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-c"               mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-cd"              mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-d"               mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-dd"              mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-raw"             mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-log"             mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-nocall"          mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-trim"            mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-trim_alt"        mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-trim_cutoff"     mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-trim_fasta"      mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-trim_scf"        mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-trim_phd"        mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-trim_out"        mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-nonorm"          mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-nosplit"         mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-nocmpqv"         mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-ceilqv"          mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-beg_pred"        mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-exit_nomatch"    mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-process_nomatch" mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-v"               mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-tags"            mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-V"               mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-help"            mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-h"               mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-doc"             mandatory="no"  inputFile="no"  inputType=""            outputFile="no"  value="" />
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/clustalw.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/local/grendel/bin/clustalwWrapper" toolName="clustalw" displayName="clustalw" description="ClustalW is a general purpose multiple sequence alignment program for DNA or proteins. It produces biologically meaningful multiple sequence alignments of divergent sequences. It calculates the best match for the selected sequences, and lines them up so that the identities, similarities and differences can be seen. Evolutionary relationships can be seen via viewing Cladograms or Phylograms">

    <inputFile/>
    <outputFile/>

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>fa</extension>
        <extension>fna</extension>
        <extension>faa</extension>
        <extension>seq</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension>aln</extension>
        <extension>dnd</extension>
    </outputFiletypes>


    <parameterList>
      <parameter rank=""  switchUse="combined"   switch="-infile="       mandatory="yes" inputFile="yes"   value=""/>
      <parameter rank=""  switchUse="switchOnly" switch="-align"         mandatory="no"  inputFile="no"    value=""/>
      <parameter rank=""  switchUse="switchOnly" switch="-tree"          mandatory="no"  inputFile="no"    value=""/>
      <parameter rank=""  switchUse="switchOnly" switch="-quicktree"     mandatory="no"  inputFile="no"    value=""/>
      <parameter rank=""  switchUse="combined"   switch="-output="       mandatory="no"  inputFile="no"    value=""/>
      <parameter rank=""  switchUse="combined"   switch="-bootstrap="    mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-convert"       mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-type="         mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-negative"      mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-outorder="     mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-case"          mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-seqnos="       mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-ktuple="       mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-topdiags="     mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-window="       mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-pairgap="      mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-score"         mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-pwmatrix="     mandatory="no"  inputFile="maybe" value="" />
      <parameter rank=""  switchUse="combined"   switch="-pwdnamatrix="  mandatory="no"  inputFile="maybe" value="" />
      <parameter rank=""  switchUse="combined"   switch="-pwgapopen="    mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-pwgapext="     mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-newtree="      mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-usetree="      mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-matrix="       mandatory="no"  inputFile="maybe" value="" />
      <parameter rank=""  switchUse="combined"   switch="-dnamatrix="    mandatory="no"  inputFile="maybe" value="" />
      <parameter rank=""  switchUse="combined"   switch="-gapopen="      mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-gapext="       mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-endgaps"       mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-gapdist="      mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-nopgap"        mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-nohgap"        mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-hgapresidues=" mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-maxdiv="       mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-type="         mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-transweight="  mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-profile"       mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-newtree1="     mandatory="no"  inputFile="yes"   value=""/>
      <parameter rank=""  switchUse="combined"   switch="-newtree2="     mandatory="no"  inputFile="yes"   value=""/>
      <parameter rank=""  switchUse="combined"   switch="-usetree1="     mandatory="no"  inputFile="yes"   value=""/>
      <parameter rank=""  switchUse="combined"   switch="-usetree2="     mandatory="no"  inputFile="yes"   value=""/>
      <parameter rank=""  switchUse="switchOnly" switch="-sequences"     mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-newtree="      mandatory="no"  inputFile="yes"   value=""/>
      <parameter rank=""  switchUse="combined"   switch="-usetree="      mandatory="no"  inputFile="yes"   value=""/>
      <parameter rank=""  switchUse="switchOnly" switch="-nosecstr1"     mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-nosecstr2"     mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-secstrout="    mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-helixgap=n"    mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-strandgap=n"   mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-loopgap="      mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-terminalgap="  mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-helixendin="   mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-helixendout="  mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-strandendin="  mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-strandendout=" mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-outputtree="   mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-seed="         mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-kimura"        mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-tossgaps"      mandatory="no"  inputFile="no"    value="" />
      <parameter rank=""  switchUse="combined"   switch="-bootlabels="   mandatory="no"  inputFile="no"    value="" />
    </parameterList>

    <parameterAliasList>
      <parameterAlias switchAlias="-BOOTSTRAP" switch="-bootstrap=" switchValue="1000" />
    </parameterAliasList>



    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>
