=== lzaagg/yabi/yabi/yabi-mw/cfg/baat.dtd
<!ELEMENT baat (job+)>
<!ELEMENT job (inputFile, outputFile, parameterList, parameterAliasList, grendel, priority, executionHost, batchNumber, status, startTime, stopTime, submittedTime, submitUser, submitLabel)>
<!ELEMENT inputFile (#PCDATA)>
<!ELEMENT outputFile (#PCDATA)>
<!ELEMENT parameterList (parameter+)>
<!ELEMENT parameterAliasList (parameterAlias+)>
<!ELEMENT grendel (option*)>
<!ELEMENT priority (#PCDATA)>
<!ELEMENT executionHost (#PCDATA)>
<!ELEMENT batchNumber (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT startTime (#PCDATA)>
<!ELEMENT stopTime (#PCDATA)>
<!ELEMENT submittedTime (#PCDATA)>
<!ELEMENT submitUser (#PCDATA)>
<!ELEMENT submitLabel (#PCDATA)>
<!ELEMENT parameter (#PCDATA)>
<!ELEMENT option (name, value)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST job toolPath CDATA #IMPLIED>
<!ATTLIST job toolName CDATA #IMPLIED>
<!ATTLIST parameter name CDATA #IMPLIED>
<!ATTLIST parameter mandatory CDATA #IMPLIED>
<!ATTLIST parameter switchUse CDATA #IMPLIED>
<!ATTLIST parameter switch CDATA #IMPLIED>
<!ATTLIST parameter value CDATA #IMPLIED>
<!ATTLIST parameter rank CDATA #IMPLIED>
<!ATTLIST parameter inputFile CDATA #IMPLIED>
<!ATTLIST parameter outputFile CDATA #IMPLIED>
<!ATTLIST parameterAlias switchAlias CDATA #IMPLIED>
<!ATTLIST parameterAlias switch CDATA #IMPLIED>
<!ATTLIST parameterAlias switchValue CDATA #IMPLIED>
<!ATTLIST grendel id CDATA #IMPLIED>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/directoryselector.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="" toolName="directoryselector" displayName="select directory" description="Select a directory from your workspace directory.">

    <inputFile/>
    <outputFile/>

    <inputFiletypes requiresInput="false" acceptsInput="false">
        <extension>*</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension>*</extension>
    </outputFiletypes>

    <parameterList/>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/yabixml2fasta.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/local/bin/ccg-formatconvertor" toolName="2fasta" displayName="extract fasta" description="Converts yabi xml format to FASTA format.">

    <inputFile/>
    <outputFile/>

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>xml</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension>fa</extension>
    </outputFiletypes>

    <parameterList>
      <parameter rank="1" switchUse="valueOnly" switch="inputFiles" mandatory="yes" inputFile="yes" outputFile="no" value=""/>
      <parameter rank="2" switchUse="valueOnly" switch="" mandatory="yes" inputFile="no" outputFile="no" value="yabixml"/>
      <parameter rank="3" switchUse="valueOnly" switch="" mandatory="yes" inputFile="no" outputFile="no" value="fasta"/>
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/blastpgp.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/local/grendel/bin/blastpgpWrapper" toolName="blastpgp" displayName="blastpgp" description="Blastpgp is part of the BLAST software package from the NCBI that performs gapped blastp searches, and can also be used to perform iterative searches in psi-blast and phi-blast mode. Blastpgp requires a protein fasta">

    <inputFile/>
    <outputFile/>

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>fa</extension>
        <extension>fna</extension>
        <extension>faa</extension>
        <extension>seq</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension>bls</extension>
    </outputFiletypes>

    <parameterList>
      <parameter rank=""  switchUse="both"       switch="-A" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-B" mandatory="no"  inputFile="yes"   outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-C" mandatory="no"  inputFile="yes"   outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-E" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-F" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-G" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-H" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-I" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-J" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-K" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-L" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-M" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-N" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-O" mandatory="no"  inputFile="yes"   outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-P" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-Q" mandatory="no"  inputFile="yes"   outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-R" mandatory="no"  inputFile="yes"   outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-S" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-T" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-U" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-W" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-X" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-Y" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-Z" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-a" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-b" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-c" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-d" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-e" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-f" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-g" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-h" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-i" mandatory="yes" inputFile="yes"   outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-j" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-k" mandatory="no"  inputFile="yes"   outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-l" mandatory="no"  inputFile="maybe" outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-m" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-o" mandatory="no"  inputFile="no"    outputFile="yes" value="" />
      <parameter rank=""  switchUse="both"       switch="-p" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-s" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-t" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-v" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-y" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-z" mandatory="no"  inputFile="no"    outputFile="no"  value="" />
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/prointblast2html.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/local/grendel/bin/prointblast2htmlWrapper" toolName="prointblast2html" displayName="pi-blast prettyprint" description="HTML formats the output from pi-blast">

    <inputFile/>
    <outputFile/>

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>bls</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension>html</extension>
    </outputFiletypes>


    <parameterList>
      <parameter rank=""  switchUse="valueOnly"  switch="inputFiles" mandatory="no" inputFile="yes" inputType="listoffiles" outputFile="no"  value="" />
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/testdata/sample-baat.xml
<?xml version='1.0'?>
<!DOCTYPE baat SYSTEM 'http://cbbc.murdoch.edu.au/dtd/baat.dtd'>
<baat>
  <job toolPath='/usr/local/bin/blastall' toolName='blast'>

    <inputFile>data.zip</inputFile>
    <outputFile>1234567890.zip</outputFile>

    <parameterList>
      <parameter name='dataset' mandatory='Yes' switchOnly='No' switch='-d' value='nr' rank='1'/>
      <parameter name='dataset' mandatory='Yes' switchOnly='No' switch='-p' value='blastx' rank='2'/>
      <parameter name='dataset' mandatory='Yes' switchOnly='No' switch='-i' value='data.txt' rank='3'/>
      <parameter name='dataset' mandatory='Yes' switchOnly='No' switch='-d' value='nr' rank='4'/>
      <parameter name='dataset' mandatory='Yes' switchOnly='No' switch='-d' value='nr' rank='5'/>
      <parameter name='dataset' mandatory='Yes' switchOnly='No' switch='-d' value='nr' rank='6'/>
    </parameterList>

    <grendel id='1234567'>
      <option>
        <name>eric</name>
      </option>
      <option>
        <name>cache</name>
      </option>
      <option>
        <name>label</name>
        <value>igrow</value>
      </option>
    </grendel>

    <priority>-20</priority>
    <executionHost>cbbc-n09</executionHost>
    <batchNumber>1234567890</batchNumber>
    <status>C</status>
    <startTime>13 oct 2003 12:00:01</startTime>
    <stopTime>13 oct 2003 12:00:02</stopTime>
    <submittedTime>13 oct 2003 12:00:00</submittedTime>
    <submitUser>some user</submitUser>
    <submitLabel>some_random_label</submitLabel>
  </job>

</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/echo.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/bin/echo" toolName="echo">

    <inputFile/>
    <outputFile/>

    <parameterList>
        <parameter rank="1" switchUse="valueOnly" switch="text" mandatory="no" inputFile="no" outputFile="no"  value=""/>
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/getkeggid.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/local/bin/ccg-fetchkeggid" toolName="getkeggid" displayName="get KEGG id" description="Retrieves KEGG ids from GeneID or GI. This tool only accepts and produces yabixml for use with other Yabi tools.">

    <inputFile/>
    <outputFile/>

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>xml</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension>xml</extension>
    </outputFiletypes>

    <parameterList>
      <parameter rank="1" switchUse="valueOnly" switch="inputFiles" mandatory="yes" inputFile="yes" outputFile="no" value=""/>
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/clustalwtranslate.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/local/bin/ccg-clustalwtranslate" toolName="clustalwtranslate" displayName="clustalw translate" description="Takes the first sequence in a clustalw alignment and translates it from nuclotide to protein or vice versa and adds it back into the aln file.">

    <inputFile/>
    <outputFile/>

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>aln</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension>aln</extension>
    </outputFiletypes>

    <parameterList>
      <parameter rank="1" switchUse="both" switch="--input-file" mandatory="yes" inputFile="yes" outputFile="no" value=""/>
      <parameter rank="2" switchUse="both" switch="--output-file" mandatory="yes" inputFile="yes" outputFile="no" value="" sourceParam="--input-file" appendString=".aln"/>
      <parameter rank="3" switchUse="both" switch="--codon-table" mandatory="yes" inputFile="no" outputFile="no" value=""/>
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>
