=== lzaagg/yabi/yabi/yabi-mw/cfg/baat.dtd
<!ELEMENT baat (job+)>
<!ELEMENT job (inputFile, outputFile, parameterList, parameterAliasList, grendel, priority, executionHost, batchNumber, status, startTime, stopTime, submittedTime, submitUser, submitLabel)>
<!ELEMENT inputFile (#PCDATA)>
<!ELEMENT outputFile (#PCDATA)>
<!ELEMENT parameterList (parameter+)>
<!ELEMENT parameterAliasList (parameterAlias+)>
<!ELEMENT grendel (option*)>
<!ELEMENT priority (#PCDATA)>
<!ELEMENT executionHost (#PCDATA)>
<!ELEMENT batchNumber (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT startTime (#PCDATA)>
<!ELEMENT stopTime (#PCDATA)>
<!ELEMENT submittedTime (#PCDATA)>
<!ELEMENT submitUser (#PCDATA)>
<!ELEMENT submitLabel (#PCDATA)>
<!ELEMENT parameter (#PCDATA)>
<!ELEMENT option (name, value)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST job toolPath CDATA #IMPLIED>
<!ATTLIST job toolName CDATA #IMPLIED>
<!ATTLIST parameter name CDATA #IMPLIED>
<!ATTLIST parameter mandatory CDATA #IMPLIED>
<!ATTLIST parameter switchUse CDATA #IMPLIED>
<!ATTLIST parameter switch CDATA #IMPLIED>
<!ATTLIST parameter value CDATA #IMPLIED>
<!ATTLIST parameter rank CDATA #IMPLIED>
<!ATTLIST parameter inputFile CDATA #IMPLIED>
<!ATTLIST parameter outputFile CDATA #IMPLIED>
<!ATTLIST parameterAlias switchAlias CDATA #IMPLIED>
<!ATTLIST parameterAlias switch CDATA #IMPLIED>
<!ATTLIST parameterAlias switchValue CDATA #IMPLIED>
<!ATTLIST grendel id CDATA #IMPLIED>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/prettyplot.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/local/grendel/bin/prettyplotWrapper" toolName="prettyplot" displayName="prettyplot" description="Displays aligned sequences, with colouring and boxing">

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>fa</extension>
        <extension>fna</extension>
        <extension>faa</extension>
        <extension>seq</extension>
        <extension>aln</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension>png</extension>
        <extension>ps</extension>
    </outputFiletypes>
    <inputFile/>
    <outputFile/>

    <parameterList>
      <parameter rank=""  switchUse="both"       switch="-sequences"       mandatory="yes" inputFile="yes" value="" />
      <parameter rank=""  switchUse="both"       switch="-graph"           mandatory="yes" inputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-residuesperline" mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-resbreak"        mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-ccolours"        mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-noccolours"      mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-cidentity"       mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-csimilarity"     mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-cother"          mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-docolour"        mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-title"           mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-notitle"         mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-shade"           mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-pair"            mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-identity"        mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-box"             mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-nobox"           mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-boxcol"          mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-boxcolval"       mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-name"            mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-maxnamelen"      mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-number"          mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-nonumber"        mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-nolistoptions"   mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-plurarity"       mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-consensus"       mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-collision"       mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-nocollision"     mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-alternative"     mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-matrixfile"      mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-showscore"       mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-portrait"        mandatory="no"  inputFile="no"  value="" />
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/ccg-blat.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job jobType="ccg" toolPath="/usr/local/grendel/bin/blatWrapper" toolName="ccg-blat" displayName="ccg blat" description="BLAT (BLAST-Like Alignment Tool) is a very fast sequence alignment tool similar to BLAST">

    <inputFile/>
    <outputFile/>

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>fa</extension>
        <extension>fna</extension>
        <extension>faa</extension>
        <extension>seq</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension>psl</extension>
    </outputFiletypes>


    <parameterList>
      <parameter rank="1" switchUse="valueOnly"  switch="database"            mandatory="yes" inputFile="maybe" outputFile="no"  value=""/>
      <parameter rank="2" switchUse="valueOnly"  switch="queryFile"            mandatory="yes" inputFile="maybe" outputFile="no"  value=""/>
      <parameter rank="3" switchUse="valueOnly"  switch="outputFile"            mandatory="yes" inputFile="no"    outputFile="yes" value=""/>
      <parameter rank=""  switchUse="combined"   switch="-t="                mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="combined"   switch="-q="                mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="switchOnly" switch="-prot"              mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="combined"   switch="-ooc="              mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="combined"   switch="-tileSize="         mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="combined"   switch="-stepSize="         mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="combined"   switch="-oneOff="           mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="combined"   switch="-minMatch="         mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="combined"   switch="-minScore="         mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="combined"   switch="-minIdentity="      mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="combined"   switch="-maxGap="           mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="switchOnly" switch="-noHead"            mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="combined"   switch="-makeOoc="          mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="combined"   switch="-repMatch="         mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="combined"   switch="-mask="             mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="combined"   switch="-qMask="            mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="combined"   switch="-minRepDivergence=" mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="combined"   switch="-dots="             mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="switchOnly" switch="-trimT"             mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="switchOnly" switch="-noTrimA"           mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="switchOnly" switch="-trimHardA"         mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="switchOnly" switch="-fastMap"           mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="combined"   switch="-out="              mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="switchOnly" switch="-fine"              mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="combined"   switch="-maxIntron="        mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
      <parameter rank=""  switchUse="combined"   switch="-extendThroughN"    mandatory="no"  inputFile="no"    outputFile="no"  value=""/>
    </parameterList>

    <parameterAliasList/>
    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/embl2emblXml.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/local/bin/ccg-formatconvertor" toolName="embl2emblXml" displayName="embl to embl xml" description="Convert EMBL format to EMBL xml format.">

    <inputFile/>
    <outputFile/>

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>embl</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension>xml</extension>
    </outputFiletypes>

    <parameterList>
      <parameter rank="1" switchUse="valueOnly" switch="inputFiles" mandatory="yes" filter="prependUserDir" inputFile="yes" outputFile="no" value=""/>
      <parameter rank="2" switchUse="valueOnly" switch="" mandatory="yes" inputFile="no" outputFile="no" value="embl"/>
      <parameter rank="3" switchUse="valueOnly" switch="" mandatory="yes" inputFile="no" outputFile="no" value="emblXml"/>
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/gziptool.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/bin/gzip" toolName="gziptool" displayName="gzip tool" description="gzips the output of the previous node">

    <inputFile/>
    <outputFile/>


    <inputFiletypes requiresInput="true">
        <extension>*</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension>txt</extension>
    </outputFiletypes>


    <parameterList>
        <parameter rank="1" switchUse="switchOnly" switch="-r" mandatory="no" inputFile="no" outputFile="no"  value=""/>
        <parameter rank="2" switchUse="switchOnly" switch="-9" mandatory="no" inputFile="no" outputFile="no" value=""/>
        <parameter rank="3" switchUse="switchOnly" switch="-q" mandatory="no" inputFile="no" outputFile="no" value=""/>
        <parameter rank="4" switchUse="valueOnly" switch="inputFiles" mandatory="no" filter="prependUserDir" inputFile="no" outputFile="no" value=""/>
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/prss34.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/local/grendel/bin/prss34Wrapper" toolName="prss34" displayName="prss" description="evaluate the significance of a pro- tein:protein, DNA:DNA ( prss34 ), or translated-DNA:protein ( prfx34  ) sequence  similarity  score">

    <inputFile/>
    <outputFile/>

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>fa</extension>
        <extension>fna</extension>
        <extension>faa</extension>
        <extension>seq</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension>fsa</extension>
    </outputFiletypes>


    <parameterList>
      <parameter rank="0" switchUse="valueOnly"  switch="program"   mandatory="yes" inputFile="no"    outputFile="no"  value="" />
      <parameter rank="1" switchUse="valueOnly"  switch="inputFile" mandatory="yes" inputFile="yes"   outputFile="no"  value="" />
      <parameter rank="2" switchUse="valueOnly"  switch="dataSet"   mandatory="yes" inputFile="maybe" outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-A"        mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-f"        mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-g"        mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-H"        mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-k"        mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-q"        mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-O"        mandatory="no"  inputFile="no"    outputFile="yes" value="" />
      <parameter rank=""  switchUse="both"       switch="-s"        mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-v"        mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-z"        mandatory="no"  inputFile="no"    outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-Z"        mandatory="no"  inputFile="no"    outputFile="no"  value="" />
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/blasttophits.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/local/bin/ccg-blastparser" toolName="blasttophits" displayName="blast top hits" description="Parse a blast report and convert to yabi xml format for use by other tools.">

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>bls</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension>xml</extension>
    </outputFiletypes>


    <inputFile/>
    <outputFile/>

    <parameterList>
        <parameter rank="1" switchUse="valueOnly" switch="inputFiles" mandatory="yes" inputFile="yes" filter="prependUserDir" outputFile="no"  value=""/>
        <parameter rank="2" switchUse="valueOnly" switch="hitCount" mandatory="yes" inputFile="no" outputFile="no" value=""/>
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/glimmerm.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/local/grendel/bin/glimmermWrapper" toolName="glimmerm" displayName="glimmerm" description="GlimmerM is a gene finder developed specifically for small eukaryotes with a gene density of around 20% ">

    <inputFile/>
    <outputFile/>

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>fa</extension>
        <extension>fna</extension>
        <extension>faa</extension>
        <extension>seq</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension>out</extension>
    </outputFiletypes>

    <parameterList>
      <parameter rank="1" switchUse="valueOnly"  switch="inputFile" mandatory="yes" inputFile="yes" outputFile="no"  value="" />
      <parameter rank="2" switchUse="valueOnly"  switch="modelName" mandatory="yes" inputFile="no"  outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-g"      mandatory="no"  inputFile="no"  outputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-t"      mandatory="no"  inputFile="no"  outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-r"      mandatory="no"  inputFile="no"  outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="+r"      mandatory="no"  inputFile="no"  outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-f"      mandatory="no"  inputFile="no"  outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="+f"      mandatory="no"  inputFile="no"  outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-s"      mandatory="no"  inputFile="no"  outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="+s"      mandatory="no"  inputFile="no"  outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-5"      mandatory="no"  inputFile="no"  outputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-3"      mandatory="no"  inputFile="no"  outputFile="no"  value="" />
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>

=== lzaagg/yabi/yabi/yabi-mw/yabi-tools/getorf.xml
<?xml version="1.0"?>
<!DOCTYPE baat SYSTEM "http://ccg.murdoch.edu.au/dtd/baat.dtd">
<baat>
  <job toolPath="/usr/local/grendel/bin/getorfWrapper" toolName="getorf" displayName="getorf" description="Finds and extracts open reading frames (ORFs)">

    <inputFiletypes requiresInput="true" acceptsInput="true">
        <extension>fa</extension>
        <extension>fna</extension>
        <extension>faa</extension>
        <extension>seq</extension>
    </inputFiletypes>

    <outputFiletypes filePassThru="false">
        <extension>fa</extension>
    </outputFiletypes>

    <inputFile/>
    <outputFile/>

    <parameterList>
      <parameter rank=""  switchUse="both"       switch="-sequence"     mandatory="yes" inputFile="yes" value="" />
      <parameter rank=""  switchUse="both"       switch="-outseq"       mandatory="no"  inputFile="no"  value="" sourceParam="-sequence" appendString=".fa" /> 
      <parameter rank=""  switchUse="both"       switch="-table"        mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-minsize"      mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-maxsize"      mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-find"         mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-methionine"   mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-nomethionine" mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-circular"     mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-reverse"      mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="switchOnly" switch="-noreverse"    mandatory="no"  inputFile="no"  value="" />
      <parameter rank=""  switchUse="both"       switch="-flanking"     mandatory="no"  inputFile="no"  value="" />
    </parameterList>

    <parameterAliasList/>

    <grendel/>
    <priority/>
    <executionHost/>
    <batchNumber/>
    <status/>
    <startTime/>
    <stopTime/>
    <submittedTime/>
    <submitUser/>
    <submitLabel/>
  </job>
</baat>
